MEMSIZE= "10000"      # memory size for VM
HOST_NAME="BigData"
HOST_IP = "192.168.33.10"   # VM IP address
SHARED_FOLDER="D:/dataset"

Vagrant::Config.run do |config|
 
    config.vm.box = "ubuntu/trusty64"
        
    config.vm.customize [
                        "modifyvm", :id,
                        "--name", HOST_NAME,
                        "--memory", MEMSIZE,
                      ]
           
    config.vm.host_name = HOST_NAME
    config.vm.network :hostonly, HOST_IP
 
    # Set the default project share to use nfs
    config.vm.share_folder("dataset", "/vagrant/dataset/", SHARED_FOLDER, :nfs => true)
 
    # Forward a port from the guest to the host, which allows for outside
    # computers to access the VM, whereas host only networking does not.
    config.vm.forward_port 8080 , 8080 #spark WEB UI master
    config.vm.forward_port 7077, 7077 #spark master
    config.vm.forward_port 4040, 4040 #spark history
    config.vm.forward_port 9042, 9042 #cassandra
    config.vm.forward_port 2181, 2181 #zookeeper
    config.vm.forward_port 9092, 9092 #kafka
    config.vm.forward_port 9200, 9200 #elastic
    config.vm.forward_port 5601, 5601 #kibana
    config.vm.forward_port 9995, 9995 #zeppelin
 
 
    config.vm.provision :shell, :inline => "/bin/sh /vagrant/install/install.sh"
 
end